// This key is domain-restricted, don't even try.
const API_KEY = "J9HxCuZ903G6MABPdFn6";

const mapStyle = {
  version: 8,
  sources: {
    maptiler_planet: {
      url: `https://api.maptiler.com/tiles/v3/tiles.json?key=${API_KEY}`,
      type: "vector",
    },
    satellite: {
      url: `https://api.maptiler.com/tiles/satellite-v2/tiles.json?key=${API_KEY}`,
      type: "raster",
    },
    terrainSource: {
      type: "raster-dem",
      url: `https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=${API_KEY}`,
      tileSize: 256,
    },
    hillshadeSource: {
      type: "raster-dem",
      url: `https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=${API_KEY}`,
      tileSize: 256,
    },
  },
  glyphs: `https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=${API_KEY}`,
  sprite: "https://api.maptiler.com/maps/outdoor-v2/sprite",
  layers: [
    {
      id: "satellite",
      type: "raster",
      source: "satellite",
    },
    {
      id: "hills",
      type: "hillshade",
      source: "hillshadeSource",
      layout: { visibility: "visible" },
      paint: {
        "hillshade-shadow-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          "hsl(9, 3%, 41%)",
          13,
          "hsl(9, 0%, 0%)",
          15,
          "hsl(9, 3%, 41%)",
        ],
        "hillshade-highlight-color": "hsl(20, 13%, 68%)",
        "hillshade-accent-color": "hsl(98, 35%, 86%)",
        "hillshade-illumination-anchor": "map",
        "hillshade-illumination-direction": 180,
        "hillshade-exaggeration": {
          stops: [
            [6, 0.4],
            [14, 0.35],
            [18, 0.25],
          ],
        },
      },
    },
    // Taken from MapTiler Outdoor style
    // See https://cloud.maptiler.com/maps/outdoor-v2/
    {
      id: "Peak labels",
      type: "symbol",
      source: "maptiler_planet",
      "source-layer": "mountain_peak",
      minzoom: 9,
      maxzoom: 22,
      layout: {
        "icon-size": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          9,
          ["case", ["==", ["get", "rank"], 1], 0.9, 0.7],
          14,
          ["case", ["==", ["get", "rank"], 1], 1, 0.8],
        ],
        "text-font": ["Roboto Condensed Regular", "Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["exponential", 1],
          ["zoom"],
          7,
          9,
          11,
          10,
          13,
          13,
        ],
        "icon-image": "triangle",
        "text-field": [
          "concat",
          ["coalesce", ["get", "name:en"], ["get", "name"]],
          " ",
          ["get", "ele"],
          " m",
        ],
        visibility: "visible",
        "text-anchor": "top",
        "text-offset": [0, 0.7],
        "text-max-width": {
          stops: [
            [12, 4],
            [15, 4],
          ],
        },
      },
      paint: {
        "icon-color": "hsl(23, 57%, 24%)",
        "text-color": "hsl(23, 57%, 24%)",
        "icon-halo-blur": 0.2,
        "text-halo-blur": {
          stops: [
            [11, 2],
            [15, 0],
          ],
        },
        "icon-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-width": ["interpolate", ["linear"], ["zoom"], 9, 1, 14, 1.5],
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": ["interpolate", ["linear"], ["zoom"], 9, 1, 14, 1.5],
      },
      filter: [
        "all",
        ["==", "$type", "Point"],
        ["in", "class", "peak"],
        ["has", "name"],
        ["!has", "customary_ft"],
      ],
    },
    {
      id: "Town labels",
      type: "symbol",
      source: "maptiler_planet",
      "source-layer": "place",
      minzoom: 6,
      maxzoom: 16,
      layout: {
        "icon-size": 0.7,
        "text-font": ["Roboto Medium", "Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          6,
          ["case", ["<=", ["get", "rank"], 12], 11, 10],
          9,
          ["case", ["<=", ["get", "rank"], 15], 13, 12],
          16,
          ["case", ["<=", ["get", "rank"], 15], 22, 20],
        ],
        "icon-image": "dot",
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        visibility: "visible",
        "icon-anchor": "top",
        "text-anchor": "bottom",
        "text-offset": [0, 0.1],
        "text-max-width": 8,
      },
      paint: {
        "icon-color": "hsl(0, 0%, 100%)",
        "text-color": "hsl(240, 6%, 13%)",
        "icon-halo-blur": 0,
        "icon-halo-color": "hsl(0, 0%, 35%)",
        "icon-halo-width": 1,
        "text-halo-color": "hsla(0, 100%, 100%, 0.8)",
        "text-halo-width": 1.6,
      },
      metadata: {},
      filter: ["==", "class", "town"],
    },
    {
      id: "City labels",
      type: "symbol",
      source: "maptiler_planet",
      "source-layer": "place",
      minzoom: 5,
      maxzoom: 16,
      layout: {
        "icon-size": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          6,
          ["match", ["get", "capital"], 2, 0.7, 0.6],
          14,
          ["match", ["get", "capital"], 2, 0.9, 0.7],
        ],
        "text-font": ["Roboto Medium", "Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          5,
          ["case", ["==", ["get", "capital"], 2], 16, 12],
          7,
          ["case", ["==", ["get", "capital"], 2], 18, 14],
          9,
          ["case", ["==", ["get", "capital"], 2], 25, 22],
          11,
          ["case", ["==", ["get", "capital"], 2], 28, 24],
        ],
        "icon-image": "circle-dot",
        "text-field": "{name:en}",
        visibility: "visible",
        "icon-offset": [
          "interpolate",
          ["linear"],
          ["zoom"],
          6,
          ["literal", [0, 0]],
          10,
          ["literal", [0, -2]],
        ],
        "text-anchor": "bottom",
        "text-padding": 2,
        "icon-optional": false,
        "text-max-width": 8,
        "symbol-sort-key": ["to-number", ["get", "rank"]],
        "icon-allow-overlap": false,
      },
      paint: {
        "text-color": "hsl(240, 6%, 13%)",
        "text-translate": [0, -2],
        "icon-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-width": 1,
        "text-halo-color": "hsla(0, 100%, 100%, 0.8)",
        "text-halo-width": 1.6,
      },
      metadata: {},
      filter: ["==", "class", "city"],
    },
    {
      id: "Village labels",
      type: "symbol",
      source: "maptiler_planet",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 22,
      layout: {
        "icon-size": 0.5,
        "text-font": ["Roboto Regular", "Noto Sans Regular"],
        "text-size": ["interpolate", ["linear", 1], ["zoom"], 11, 12, 16, 18],
        "icon-image": "dot",
        "text-field": "{name}",
        visibility: "visible",
        "text-anchor": "bottom",
        "text-offset": [0, -0.2],
        "text-max-width": 8,
        "text-transform": "none",
        "icon-allow-overlap": true,
        "text-letter-spacing": 0,
      },
      paint: {
        "icon-color": "hsl(0, 0%, 100%)",
        "text-color": "hsl(240, 6%, 13%)",
        "icon-halo-blur": 0,
        "icon-halo-color": "hsl(0, 0%, 35%)",
        "icon-halo-width": 1,
        "text-halo-color": "hsla(0, 100%, 100%, 0.8)",
        "text-halo-width": 1.6,
      },
      filter: ["==", "class", "village"],
    },
  ],
  terrain: {
    source: "terrainSource",
    exaggeration: 1,
  },
};

// Taken from https://maplibre.org/maplibre-style-spec/sky/
const skyStyle = {
  "sky-color": "#199EF3",
  "sky-horizon-blend": 0.5,
  "horizon-color": "#ffffff",
  "horizon-fog-blend": 0.5,
  "fog-color": "#0000ff",
  "fog-ground-blend": 0.5,
  "atmosphere-blend": ["interpolate", ["linear"], ["zoom"], 0, 1, 10, 1, 12, 0],
};

export { mapStyle, skyStyle };
